[project]
name = "compressarc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib==3.10.0",
    "numpy==2.2.2",
    "torch==2.5.1",
    "tqdm==4.66.6",
]

[dependency-groups]
dev = [
    "ruff>=0.14.1",
]
